added stores: Bol.com (NL), FNAC (FR) and Mediamarkt (NL), updated st…
jef/streetmerchant pull request #1099
Opened 2020-12-02 17:15 UTC by johnneerdael

…ores: Amazon (NL) and Coolblue (NL) to add PS5 console support

### Description

### Testing

### New dependencies

2020-12-02 21:35 UTC, jef requested changes

2020-12-02 21:35 UTC, jef commented on src/store/model/bol.ts
> +			text: ['Op voorraad']
```suggestion
			container: 'div[data-test="buy-block__options"]',
			text: ['In winkelwagen']
```

Isn't this the correct verbiage?

2020-12-02 21:35 UTC, jef commented on src/store/model/bol.ts
> +			container: 'span[class*="PriceString"]',
```suggestion
			container: '.price-block__price',
```

or

```suggestion
			container: '.promo-price',
```

But not sure how reliable that is. `promo` makes it seem like it's temporary.

2020-12-02 21:35 UTC, jef commented on src/store/model/fnac.ts
> +				'https://www.fnac.com/Console-Sony-PS5-Edition-Standard/a14119956/w-4'
Could you change to something that is a better test candidate? Something that is usually in stock?

2020-12-02 21:35 UTC, jef commented on src/store/model/mediamarkt-nl.ts
> +			text: ['Online op voorraad']
```suggestion
			container: 'div.price-button',
			text: ['bestel nu']
```

Isn't this what you'd want?

![image](https://user-images.githubusercontent.com/12074633/100934190-651fa200-34bc-11eb-9301-da7b8687448d.png)

2021-01-07 00:35 UTC, closed without merging

2021-06-01 12:01 UTC, Revadike commented
We need this added!

2021-06-03 19:29 UTC, Revadike commented
@johnneerdael could you perhaps update this?

2021-06-15 19:12 UTC, jef commented
@Revadike, if you want to take it over, I'll add!