feat: discord notification groups
jef/streetmerchant pull request #1211
Opened 2020-12-06 08:18 UTC by styler2go

### Description

I have added the option to select specific discord groups for each series. I made it because it was requested in my discord. If you don't need it feel free to decline/close this request

2020-12-07 13:38 UTC, jef requested changes
This is great! I know I've been asked for this a few times now!

If you could just make the documentation change, that would be great.

---

I think this is also another reason why I have been working on https://github.com/jef/streetmerchant/tree/prerelease/4.0.0.

Config drift is hellish 🙃

2020-12-07 13:38 UTC, jef commented on docs/reference/notification.md
> +| `DISCORD_NOTIFY_GROUP_TEST` | Discord group to notify on test stock | Same as `DISCORD_NOTIFY_GROUP` |
```suggestion
| `DISCORD_NOTIFY_GROUP_3060TI` | Discord group to notify on 3060 Ti stock |
| `DISCORD_NOTIFY_GROUP_3070` | Discord group to notify on 3070 stock |
| `DISCORD_NOTIFY_GROUP_3080` | Discord group to notify on 3080 stock |
| `DISCORD_NOTIFY_GROUP_3090` | Discord group to notify on 3090 stock |
| `DISCORD_NOTIFY_GROUP_RYZEN5600` | Discord group to notify on 5600X stock |
| `DISCORD_NOTIFY_GROUP_RYZEN5800` | Discord group to notify on 5800X stock |
| `DISCORD_NOTIFY_GROUP_RYZEN5900` | Discord group to notify on 5900X stock |
| `DISCORD_NOTIFY_GROUP_RYZEN5950` | Discord group to notify on 5950X stock |
| `DISCORD_NOTIFY_GROUP_CORSAIR_SF` | Discord group to notify on Corsair SF stock |
| `DISCORD_NOTIFY_GROUP_SONYPS5C` | Discord group to notify on Sony PS5 stock |
| `DISCORD_NOTIFY_GROUP_SONYPS5DE` | Discord group to notify on Sony PS5 Digital stock |
| `DISCORD_NOTIFY_GROUP_TEST` | Discord group to notify on test stock |
```

Perhaps you can add to the note at the bottom saying `DISCORD_NOTIFY_GROUP` will take care of everything or something?

2020-12-08 16:53 UTC, jef requested changes
Just a couple more things and we'll be there!

Thank you very much!!!

2020-12-08 16:53 UTC, jef commented on src/notification/discord.ts
> +				embed.setColor(0x76b900);
Color is already set on line 36

2020-12-08 16:53 UTC, jef commented on docs/reference/notification.md
> +    something like `" "` or don't set `DISCORD_NOTIFY_GROUP`.
```suggestion
    If you don't assign a value to a series group it will always fallback to `DISCORD_NOTIFY_GROUP`.
```

2020-12-08 20:06 UTC, styler2go commented on src/notification/discord.ts
> +				embed.setColor(0x76b900);
```suggestion
```

2020-12-09 08:29 UTC, styler2go commented on docs/reference/notification.md
> +    something like `" "` or don't set `DISCORD_NOTIFY_GROUP`.
```suggestion
???+ note
    If you don't assign a value to a series group it will always fallback to `DISCORD_NOTIFY_GROUP`.
```

2020-12-09 19:54 UTC, jef approved these changes
Awesome! Thank you very much for all your work!

2020-12-09 19:54 UTC, merged