feat(philips_hue): Add Philips Hue notification support over either LAN or Cloud
jef/streetmerchant pull request #681
Opened 2020-11-04 00:58 UTC by MattieX

### Description
Added Philips Hue notification support over LAN or Cloud using Node-Hue-Api (See https://www.npmjs.com/package/node-hue-api).

Can set the color of the lights, whether they should blink, and individual light IDs to adjust.

<details>
<summary>Required Variables</summary>

| Environment variable | Description | Notes |
|:---:|---|---|
| `HUE_API_KEY` | Hue Bridge API Key | **Required**, generate key using instructions [here](https://developers.meethue.com/develop/get-started-2/). This will be used for both LAN and cloud access over the official Remote Hue API. |
| `HUE_LAN_BRIDGE_IP` | LAN IP Address of your Hue Bridge | LAN only, e.g. `192.168.x.x`|
| `HUE_LIGHT_IDS` | Light IDs | Optional (all if not supplied). Comma seperated, e.g.: `1`, `2` |See Hue App → About for IDs |
| `HUE_LIGHT_COLOR` | Color in RGB Format | Optional (NVIDIA green if not supplied). Comma separated, e.g.: `255`, `255`, `255`|
| `HUE_LIGHT_PATTERN` | `blink` or empty | Optional - lights will flash for 30 seconds if `blink` is supplied. |
| `HUE_CLOUD_ACCESS_TOKEN` | Remote Access Token | Cloud only, the access token obtained from Philips's Remote Hue API. Instructions to generate [here](https://developers.meethue.com/develop/hue-api/remote-authentication/). |
| `HUE_CLOUD_REFRESH_TOKEN` | Remote Refresh Token | Cloud only, the refresh token obtained from Philips's Remote Hue API.  |
| `HUE_CLOUD_CLIENT_ID` | Remote Client ID | Cloud only, the client ID to use when accessing the Remote Hue API. |
| `HUE_CLOUD_CLIENT_SECRET` | Remote Client Secret | Cloud only, the client secret to use when accessing the Remote Hue API.   |

</details>

### Testing
Used `npm run test:notification` after filling in required environment variables, observed the resulting change in Hue lights.
 

### New dependencies
[`node-hue-api`](https://www.npmjs.com/package/node-hue-api)

2020-11-04 20:36 UTC, jef commented
LOL... This is pretty awesome. I'd love to see this come in. If you have any demo to video that would be actually amazing.

2020-11-04 22:35 UTC, banksio commented
Checks should all be passing now, please let us know if we need to make any changes!

2020-11-04 23:03 UTC, MattieX commented
> LOL... This is pretty awesome. I'd love to see this come in. If you have any demo to video that would be actually amazing.

Sure! [Here](https://www.youtube.com/watch?v=EI2fWgsLOkg) you are.

2020-11-04 23:56 UTC, shortywz commented
> > LOL... This is pretty awesome. I'd love to see this come in. If you have any demo to video that would be actually amazing.
> 
> Sure! https://www.youtube.com/watch?v=EI2fWgsLOkg you are.

**This** is what open source is all about 😄

2020-11-05 21:17 UTC, jef commented
> > LOL... This is pretty awesome. I'd love to see this come in. If you have any demo to video that would be actually amazing.
> 
> Sure! [youtube.com/watch?v=EI2fWgsLOkg](https://www.youtube.com/watch?v=EI2fWgsLOkg) you are.

Omg... I love it.

Thank YOU!

2020-11-05 21:19 UTC, jef requested changes
Overall, looks pretty good! Just a couple things and we can get this in!

2020-11-05 21:19 UTC, jef commented on README.md
> +<details>
```suggestion
```

I don't think we want this one here.

2020-11-05 21:19 UTC, jef commented on src/notification/philips-hue.ts
> +const adjustLightsWithAPI = (hueBridge: import('node-hue-api/lib/api/Api')) => {
I'd prefer you import the type above and use here.

2020-11-05 23:22 UTC, jef approved these changes
AWESOME! Thank you!

2020-11-05 23:23 UTC, merged

2020-11-05 23:25 UTC, jef commented
@MattieX, do you mind if I link your video in the README?

2020-11-06 00:05 UTC, MattieX commented
> @MattieX, do you mind if I link your video in the README?

Sure - I've updated it to include the new project name now. Here you are: https://vimeo.com/476083242

2020-11-06 16:16 UTC, jef commented
That's thoughtful of you! Thanks for doing that. I'll add now!