Adds AM3 to microcenter
jef/streetmerchant pull request #707
Opened 2020-11-06 16:32 UTC by AndyGOBrien

### Description

This just adds AM3 processors to the microcenter store.

2020-11-06 21:40 UTC, jef requested changes

2020-11-06 21:40 UTC, jef commented on src/store/model/microcenter.ts
> +				url: `microcenter.com/product/630283/amd-ryzen-9-5900x-vermeer-37ghz-12-core-am4-boxed-processor/?storeid=${storeId}`
```suggestion
				url: `https://www.microcenter.com/product/630283/amd-ryzen-9-5900x-vermeer-37ghz-12-core-am4-boxed-processor/?storeid=${storeId}`
```

2020-11-06 21:40 UTC, jef commented
Looks good otherwise; Thanks!

2020-11-07 17:01 UTC, AndyGOBrien commented
@jef Just bumping this, can I get your signature real quick?

2020-11-07 17:18 UTC, jef approved these changes
Looks good to me! Thanks!

2020-11-07 17:18 UTC, merged